<?php

/**
 * Base class that represents a row from the 'element' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Tue Jan 26 18:15:54 2010
 *
 * @package    lib.model.om
 */
abstract class BaseElement extends BaseObject  implements Persistent {


	/**
	 * The Peer class.
	 * Instance provides a convenient way of calling static methods on a class
	 * that calling code may not be able to identify.
	 * @var        ElementPeer
	 */
	protected static $peer;

	/**
	 * The value for the id field.
	 * @var        int
	 */
	protected $id;

	/**
	 * The value for the category_id field.
	 * @var        int
	 */
	protected $category_id;

	/**
	 * The value for the element_status_id field.
	 * @var        int
	 */
	protected $element_status_id;

	/**
	 * The value for the company_id field.
	 * @var        int
	 */
	protected $company_id;

	/**
	 * The value for the name field.
	 * @var        string
	 */
	protected $name;

	/**
	 * The value for the title field.
	 * @var        string
	 */
	protected $title;

	/**
	 * The value for the date_created field.
	 * @var        string
	 */
	protected $date_created;

	/**
	 * The value for the date_updated field.
	 * @var        string
	 */
	protected $date_updated;

	/**
	 * The value for the preview field.
	 * @var        string
	 */
	protected $preview;

	/**
	 * The value for the description field.
	 * @var        string
	 */
	protected $description;

	/**
	 * The value for the view_count field.
	 * @var        int
	 */
	protected $view_count;

	/**
	 * The value for the order_count field.
	 * @var        int
	 */
	protected $order_count;

	/**
	 * The value for the owner_price field.
	 * @var        string
	 */
	protected $owner_price;

	/**
	 * The value for the company_price field.
	 * @var        string
	 */
	protected $company_price;

	/**
	 * The value for the price_type field.
	 * @var        int
	 */
	protected $price_type;

	/**
	 * @var        Category
	 */
	protected $aCategory;

	/**
	 * @var        ElementStatus
	 */
	protected $aElementStatus;

	/**
	 * @var        Company
	 */
	protected $aCompany;

	/**
	 * @var        array Preference[] Collection to store aggregation of Preference objects.
	 */
	protected $collPreferences;

	/**
	 * @var        Criteria The criteria used to select the current contents of collPreferences.
	 */
	private $lastPreferenceCriteria = null;

	/**
	 * @var        array Order[] Collection to store aggregation of Order objects.
	 */
	protected $collOrders;

	/**
	 * @var        Criteria The criteria used to select the current contents of collOrders.
	 */
	private $lastOrderCriteria = null;

	/**
	 * @var        array ElementFile[] Collection to store aggregation of ElementFile objects.
	 */
	protected $collElementFiles;

	/**
	 * @var        Criteria The criteria used to select the current contents of collElementFiles.
	 */
	private $lastElementFileCriteria = null;

	/**
	 * Flag to prevent endless save loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInSave = false;

	/**
	 * Flag to prevent endless validation loop, if this object is referenced
	 * by another object which falls in this transaction.
	 * @var        boolean
	 */
	protected $alreadyInValidation = false;

	// symfony behavior
	
	const PEER = 'ElementPeer';

	/**
	 * Get the [id] column value.
	 * 
	 * @return     int
	 */
	public function getId()
	{
		return $this->id;
	}

	/**
	 * Get the [category_id] column value.
	 * 
	 * @return     int
	 */
	public function getCategoryId()
	{
		return $this->category_id;
	}

	/**
	 * Get the [element_status_id] column value.
	 * 
	 * @return     int
	 */
	public function getElementStatusId()
	{
		return $this->element_status_id;
	}

	/**
	 * Get the [company_id] column value.
	 * 
	 * @return     int
	 */
	public function getCompanyId()
	{
		return $this->company_id;
	}

	/**
	 * Get the [name] column value.
	 * 
	 * @return     string
	 */
	public function getName()
	{
		return $this->name;
	}

	/**
	 * Get the [title] column value.
	 * 
	 * @return     string
	 */
	public function getTitle()
	{
		return $this->title;
	}

	/**
	 * Get the [optionally formatted] temporal [date_created] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDateCreated($format = 'Y-m-d H:i:s')
	{
		if ($this->date_created === null) {
			return null;
		}


		if ($this->date_created === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date_created);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date_created, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [optionally formatted] temporal [date_updated] column value.
	 * 
	 *
	 * @param      string $format The date/time format string (either date()-style or strftime()-style).
	 *							If format is NULL, then the raw DateTime object will be returned.
	 * @return     mixed Formatted date/time value as string or DateTime object (if format is NULL), NULL if column is NULL, and 0 if column value is 0000-00-00 00:00:00
	 * @throws     PropelException - if unable to parse/validate the date/time value.
	 */
	public function getDateUpdated($format = 'Y-m-d H:i:s')
	{
		if ($this->date_updated === null) {
			return null;
		}


		if ($this->date_updated === '0000-00-00 00:00:00') {
			// while technically this is not a default value of NULL,
			// this seems to be closest in meaning.
			return null;
		} else {
			try {
				$dt = new DateTime($this->date_updated);
			} catch (Exception $x) {
				throw new PropelException("Internally stored date/time/timestamp value could not be converted to DateTime: " . var_export($this->date_updated, true), $x);
			}
		}

		if ($format === null) {
			// Because propel.useDateTimeClass is TRUE, we return a DateTime object.
			return $dt;
		} elseif (strpos($format, '%') !== false) {
			return strftime($format, $dt->format('U'));
		} else {
			return $dt->format($format);
		}
	}

	/**
	 * Get the [preview] column value.
	 * 
	 * @return     string
	 */
	public function getPreview()
	{
		return $this->preview;
	}

	/**
	 * Get the [description] column value.
	 * 
	 * @return     string
	 */
	public function getDescription()
	{
		return $this->description;
	}

	/**
	 * Get the [view_count] column value.
	 * 
	 * @return     int
	 */
	public function getViewCount()
	{
		return $this->view_count;
	}

	/**
	 * Get the [order_count] column value.
	 * 
	 * @return     int
	 */
	public function getOrderCount()
	{
		return $this->order_count;
	}

	/**
	 * Get the [owner_price] column value.
	 * 
	 * @return     string
	 */
	public function getOwnerPrice()
	{
		return $this->owner_price;
	}

	/**
	 * Get the [company_price] column value.
	 * 
	 * @return     string
	 */
	public function getCompanyPrice()
	{
		return $this->company_price;
	}

	/**
	 * Get the [price_type] column value.
	 * 
	 * @return     int
	 */
	public function getPriceType()
	{
		return $this->price_type;
	}

	/**
	 * Set the value of [id] column.
	 * 
	 * @param      int $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->id !== $v) {
			$this->id = $v;
			$this->modifiedColumns[] = ElementPeer::ID;
		}

		return $this;
	} // setId()

	/**
	 * Set the value of [category_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setCategoryId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->category_id !== $v) {
			$this->category_id = $v;
			$this->modifiedColumns[] = ElementPeer::CATEGORY_ID;
		}

		if ($this->aCategory !== null && $this->aCategory->getId() !== $v) {
			$this->aCategory = null;
		}

		return $this;
	} // setCategoryId()

	/**
	 * Set the value of [element_status_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setElementStatusId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->element_status_id !== $v) {
			$this->element_status_id = $v;
			$this->modifiedColumns[] = ElementPeer::ELEMENT_STATUS_ID;
		}

		if ($this->aElementStatus !== null && $this->aElementStatus->getId() !== $v) {
			$this->aElementStatus = null;
		}

		return $this;
	} // setElementStatusId()

	/**
	 * Set the value of [company_id] column.
	 * 
	 * @param      int $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setCompanyId($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->company_id !== $v) {
			$this->company_id = $v;
			$this->modifiedColumns[] = ElementPeer::COMPANY_ID;
		}

		if ($this->aCompany !== null && $this->aCompany->getId() !== $v) {
			$this->aCompany = null;
		}

		return $this;
	} // setCompanyId()

	/**
	 * Set the value of [name] column.
	 * 
	 * @param      string $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setName($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->name !== $v) {
			$this->name = $v;
			$this->modifiedColumns[] = ElementPeer::NAME;
		}

		return $this;
	} // setName()

	/**
	 * Set the value of [title] column.
	 * 
	 * @param      string $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setTitle($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->title !== $v) {
			$this->title = $v;
			$this->modifiedColumns[] = ElementPeer::TITLE;
		}

		return $this;
	} // setTitle()

	/**
	 * Sets the value of [date_created] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Element The current object (for fluent API support)
	 */
	public function setDateCreated($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date_created !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date_created !== null && $tmpDt = new DateTime($this->date_created)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date_created = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ElementPeer::DATE_CREATED;
			}
		} // if either are not null

		return $this;
	} // setDateCreated()

	/**
	 * Sets the value of [date_updated] column to a normalized version of the date/time value specified.
	 * 
	 * @param      mixed $v string, integer (timestamp), or DateTime value.  Empty string will
	 *						be treated as NULL for temporal objects.
	 * @return     Element The current object (for fluent API support)
	 */
	public function setDateUpdated($v)
	{
		// we treat '' as NULL for temporal objects because DateTime('') == DateTime('now')
		// -- which is unexpected, to say the least.
		if ($v === null || $v === '') {
			$dt = null;
		} elseif ($v instanceof DateTime) {
			$dt = $v;
		} else {
			// some string/numeric value passed; we normalize that so that we can
			// validate it.
			try {
				if (is_numeric($v)) { // if it's a unix timestamp
					$dt = new DateTime('@'.$v, new DateTimeZone('UTC'));
					// We have to explicitly specify and then change the time zone because of a
					// DateTime bug: http://bugs.php.net/bug.php?id=43003
					$dt->setTimeZone(new DateTimeZone(date_default_timezone_get()));
				} else {
					$dt = new DateTime($v);
				}
			} catch (Exception $x) {
				throw new PropelException('Error parsing date/time value: ' . var_export($v, true), $x);
			}
		}

		if ( $this->date_updated !== null || $dt !== null ) {
			// (nested ifs are a little easier to read in this case)

			$currNorm = ($this->date_updated !== null && $tmpDt = new DateTime($this->date_updated)) ? $tmpDt->format('Y-m-d H:i:s') : null;
			$newNorm = ($dt !== null) ? $dt->format('Y-m-d H:i:s') : null;

			if ( ($currNorm !== $newNorm) // normalized values don't match 
					)
			{
				$this->date_updated = ($dt ? $dt->format('Y-m-d H:i:s') : null);
				$this->modifiedColumns[] = ElementPeer::DATE_UPDATED;
			}
		} // if either are not null

		return $this;
	} // setDateUpdated()

	/**
	 * Set the value of [preview] column.
	 * 
	 * @param      string $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setPreview($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->preview !== $v) {
			$this->preview = $v;
			$this->modifiedColumns[] = ElementPeer::PREVIEW;
		}

		return $this;
	} // setPreview()

	/**
	 * Set the value of [description] column.
	 * 
	 * @param      string $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setDescription($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->description !== $v) {
			$this->description = $v;
			$this->modifiedColumns[] = ElementPeer::DESCRIPTION;
		}

		return $this;
	} // setDescription()

	/**
	 * Set the value of [view_count] column.
	 * 
	 * @param      int $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setViewCount($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->view_count !== $v) {
			$this->view_count = $v;
			$this->modifiedColumns[] = ElementPeer::VIEW_COUNT;
		}

		return $this;
	} // setViewCount()

	/**
	 * Set the value of [order_count] column.
	 * 
	 * @param      int $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setOrderCount($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->order_count !== $v) {
			$this->order_count = $v;
			$this->modifiedColumns[] = ElementPeer::ORDER_COUNT;
		}

		return $this;
	} // setOrderCount()

	/**
	 * Set the value of [owner_price] column.
	 * 
	 * @param      string $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setOwnerPrice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->owner_price !== $v) {
			$this->owner_price = $v;
			$this->modifiedColumns[] = ElementPeer::OWNER_PRICE;
		}

		return $this;
	} // setOwnerPrice()

	/**
	 * Set the value of [company_price] column.
	 * 
	 * @param      string $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setCompanyPrice($v)
	{
		if ($v !== null) {
			$v = (string) $v;
		}

		if ($this->company_price !== $v) {
			$this->company_price = $v;
			$this->modifiedColumns[] = ElementPeer::COMPANY_PRICE;
		}

		return $this;
	} // setCompanyPrice()

	/**
	 * Set the value of [price_type] column.
	 * 
	 * @param      int $v new value
	 * @return     Element The current object (for fluent API support)
	 */
	public function setPriceType($v)
	{
		if ($v !== null) {
			$v = (int) $v;
		}

		if ($this->price_type !== $v) {
			$this->price_type = $v;
			$this->modifiedColumns[] = ElementPeer::PRICE_TYPE;
		}

		return $this;
	} // setPriceType()

	/**
	 * Indicates whether the columns in this object are only set to default values.
	 *
	 * This method can be used in conjunction with isModified() to indicate whether an object is both
	 * modified _and_ has some values set which are non-default.
	 *
	 * @return     boolean Whether the columns in this object are only been set with default values.
	 */
	public function hasOnlyDefaultValues()
	{
		// otherwise, everything was equal, so return TRUE
		return true;
	} // hasOnlyDefaultValues()

	/**
	 * Hydrates (populates) the object variables with values from the database resultset.
	 *
	 * An offset (0-based "start column") is specified so that objects can be hydrated
	 * with a subset of the columns in the resultset rows.  This is needed, for example,
	 * for results of JOIN queries where the resultset row includes columns from two or
	 * more tables.
	 *
	 * @param      array $row The row returned by PDOStatement->fetch(PDO::FETCH_NUM)
	 * @param      int $startcol 0-based offset column which indicates which restultset column to start with.
	 * @param      boolean $rehydrate Whether this object is being re-hydrated from the database.
	 * @return     int next starting column
	 * @throws     PropelException  - Any caught Exception will be rewrapped as a PropelException.
	 */
	public function hydrate($row, $startcol = 0, $rehydrate = false)
	{
		try {

			$this->id = ($row[$startcol + 0] !== null) ? (int) $row[$startcol + 0] : null;
			$this->category_id = ($row[$startcol + 1] !== null) ? (int) $row[$startcol + 1] : null;
			$this->element_status_id = ($row[$startcol + 2] !== null) ? (int) $row[$startcol + 2] : null;
			$this->company_id = ($row[$startcol + 3] !== null) ? (int) $row[$startcol + 3] : null;
			$this->name = ($row[$startcol + 4] !== null) ? (string) $row[$startcol + 4] : null;
			$this->title = ($row[$startcol + 5] !== null) ? (string) $row[$startcol + 5] : null;
			$this->date_created = ($row[$startcol + 6] !== null) ? (string) $row[$startcol + 6] : null;
			$this->date_updated = ($row[$startcol + 7] !== null) ? (string) $row[$startcol + 7] : null;
			$this->preview = ($row[$startcol + 8] !== null) ? (string) $row[$startcol + 8] : null;
			$this->description = ($row[$startcol + 9] !== null) ? (string) $row[$startcol + 9] : null;
			$this->view_count = ($row[$startcol + 10] !== null) ? (int) $row[$startcol + 10] : null;
			$this->order_count = ($row[$startcol + 11] !== null) ? (int) $row[$startcol + 11] : null;
			$this->owner_price = ($row[$startcol + 12] !== null) ? (string) $row[$startcol + 12] : null;
			$this->company_price = ($row[$startcol + 13] !== null) ? (string) $row[$startcol + 13] : null;
			$this->price_type = ($row[$startcol + 14] !== null) ? (int) $row[$startcol + 14] : null;
			$this->resetModified();

			$this->setNew(false);

			if ($rehydrate) {
				$this->ensureConsistency();
			}

			// FIXME - using NUM_COLUMNS may be clearer.
			return $startcol + 15; // 15 = ElementPeer::NUM_COLUMNS - ElementPeer::NUM_LAZY_LOAD_COLUMNS).

		} catch (Exception $e) {
			throw new PropelException("Error populating Element object", $e);
		}
	}

	/**
	 * Checks and repairs the internal consistency of the object.
	 *
	 * This method is executed after an already-instantiated object is re-hydrated
	 * from the database.  It exists to check any foreign keys to make sure that
	 * the objects related to the current object are correct based on foreign key.
	 *
	 * You can override this method in the stub class, but you should always invoke
	 * the base method from the overridden method (i.e. parent::ensureConsistency()),
	 * in case your model changes.
	 *
	 * @throws     PropelException
	 */
	public function ensureConsistency()
	{

		if ($this->aCategory !== null && $this->category_id !== $this->aCategory->getId()) {
			$this->aCategory = null;
		}
		if ($this->aElementStatus !== null && $this->element_status_id !== $this->aElementStatus->getId()) {
			$this->aElementStatus = null;
		}
		if ($this->aCompany !== null && $this->company_id !== $this->aCompany->getId()) {
			$this->aCompany = null;
		}
	} // ensureConsistency

	/**
	 * Reloads this object from datastore based on primary key and (optionally) resets all associated objects.
	 *
	 * This will only work if the object has been saved and has a valid primary key set.
	 *
	 * @param      boolean $deep (optional) Whether to also de-associated any related objects.
	 * @param      PropelPDO $con (optional) The PropelPDO connection to use.
	 * @return     void
	 * @throws     PropelException - if this object is deleted, unsaved or doesn't have pk match in db
	 */
	public function reload($deep = false, PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("Cannot reload a deleted object.");
		}

		if ($this->isNew()) {
			throw new PropelException("Cannot reload an unsaved object.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ElementPeer::DATABASE_NAME, Propel::CONNECTION_READ);
		}

		// We don't need to alter the object instance pool; we're just modifying this instance
		// already in the pool.

		$stmt = ElementPeer::doSelectStmt($this->buildPkeyCriteria(), $con);
		$row = $stmt->fetch(PDO::FETCH_NUM);
		$stmt->closeCursor();
		if (!$row) {
			throw new PropelException('Cannot find matching row in the database to reload object values.');
		}
		$this->hydrate($row, 0, true); // rehydrate

		if ($deep) {  // also de-associate any related objects?

			$this->aCategory = null;
			$this->aElementStatus = null;
			$this->aCompany = null;
			$this->collPreferences = null;
			$this->lastPreferenceCriteria = null;

			$this->collOrders = null;
			$this->lastOrderCriteria = null;

			$this->collElementFiles = null;
			$this->lastElementFileCriteria = null;

		} // if (deep)
	}

	/**
	 * Removes this object from datastore and sets delete attribute.
	 *
	 * @param      PropelPDO $con
	 * @return     void
	 * @throws     PropelException
	 * @see        BaseObject::setDeleted()
	 * @see        BaseObject::isDeleted()
	 */
	public function delete(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("This object has already been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ElementPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		try {
			$ret = $this->preDelete($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseElement:delete:pre') as $callable)
			{
			  if ($ret = call_user_func($callable, $this, $con))
			  {
			    return;
			  }
			}

			if ($ret) {
				ElementPeer::doDelete($this, $con);
				$this->postDelete($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseElement:delete:post') as $callable)
				{
				  call_user_func($callable, $this, $con);
				}

				$this->setDeleted(true);
				$con->commit();
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Persists this object to the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All modified related objects will also be persisted in the doSave()
	 * method.  This method wraps all precipitate database operations in a
	 * single transaction.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        doSave()
	 */
	public function save(PropelPDO $con = null)
	{
		if ($this->isDeleted()) {
			throw new PropelException("You cannot save an object that has been deleted.");
		}

		if ($con === null) {
			$con = Propel::getConnection(ElementPeer::DATABASE_NAME, Propel::CONNECTION_WRITE);
		}
		
		$con->beginTransaction();
		$isInsert = $this->isNew();
		try {
			$ret = $this->preSave($con);
			// symfony_behaviors behavior
			foreach (sfMixer::getCallables('BaseElement:save:pre') as $callable)
			{
			  if (is_integer($affectedRows = call_user_func($callable, $this, $con)))
			  {
			    return $affectedRows;
			  }
			}

			if ($isInsert) {
				$ret = $ret && $this->preInsert($con);
			} else {
				$ret = $ret && $this->preUpdate($con);
			}
			if ($ret) {
				$affectedRows = $this->doSave($con);
				if ($isInsert) {
					$this->postInsert($con);
				} else {
					$this->postUpdate($con);
				}
				$this->postSave($con);
				// symfony_behaviors behavior
				foreach (sfMixer::getCallables('BaseElement:save:post') as $callable)
				{
				  call_user_func($callable, $this, $con, $affectedRows);
				}

				$con->commit();
				ElementPeer::addInstanceToPool($this);
				return $affectedRows;
			}
		} catch (PropelException $e) {
			$con->rollBack();
			throw $e;
		}
	}

	/**
	 * Performs the work of inserting or updating the row in the database.
	 *
	 * If the object is new, it inserts it; otherwise an update is performed.
	 * All related objects are also updated in this method.
	 *
	 * @param      PropelPDO $con
	 * @return     int The number of rows affected by this insert/update and any referring fk objects' save() operations.
	 * @throws     PropelException
	 * @see        save()
	 */
	protected function doSave(PropelPDO $con)
	{
		$affectedRows = 0; // initialize var to track total num of affected rows
		if (!$this->alreadyInSave) {
			$this->alreadyInSave = true;

			// We call the save method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCategory !== null) {
				if ($this->aCategory->isModified() || $this->aCategory->isNew()) {
					$affectedRows += $this->aCategory->save($con);
				}
				$this->setCategory($this->aCategory);
			}

			if ($this->aElementStatus !== null) {
				if ($this->aElementStatus->isModified() || $this->aElementStatus->isNew()) {
					$affectedRows += $this->aElementStatus->save($con);
				}
				$this->setElementStatus($this->aElementStatus);
			}

			if ($this->aCompany !== null) {
				if ($this->aCompany->isModified() || $this->aCompany->isNew()) {
					$affectedRows += $this->aCompany->save($con);
				}
				$this->setCompany($this->aCompany);
			}

			if ($this->isNew() ) {
				$this->modifiedColumns[] = ElementPeer::ID;
			}

			// If this object has been modified, then save it to the database.
			if ($this->isModified()) {
				if ($this->isNew()) {
					$pk = ElementPeer::doInsert($this, $con);
					$affectedRows += 1; // we are assuming that there is only 1 row per doInsert() which
										 // should always be true here (even though technically
										 // BasePeer::doInsert() can insert multiple rows).

					$this->setId($pk);  //[IMV] update autoincrement primary key

					$this->setNew(false);
				} else {
					$affectedRows += ElementPeer::doUpdate($this, $con);
				}

				$this->resetModified(); // [HL] After being saved an object is no longer 'modified'
			}

			if ($this->collPreferences !== null) {
				foreach ($this->collPreferences as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collOrders !== null) {
				foreach ($this->collOrders as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			if ($this->collElementFiles !== null) {
				foreach ($this->collElementFiles as $referrerFK) {
					if (!$referrerFK->isDeleted()) {
						$affectedRows += $referrerFK->save($con);
					}
				}
			}

			$this->alreadyInSave = false;

		}
		return $affectedRows;
	} // doSave()

	/**
	 * Array of ValidationFailed objects.
	 * @var        array ValidationFailed[]
	 */
	protected $validationFailures = array();

	/**
	 * Gets any ValidationFailed objects that resulted from last call to validate().
	 *
	 *
	 * @return     array ValidationFailed[]
	 * @see        validate()
	 */
	public function getValidationFailures()
	{
		return $this->validationFailures;
	}

	/**
	 * Validates the objects modified field values and all objects related to this table.
	 *
	 * If $columns is either a column name or an array of column names
	 * only those columns are validated.
	 *
	 * @param      mixed $columns Column name or an array of column names.
	 * @return     boolean Whether all columns pass validation.
	 * @see        doValidate()
	 * @see        getValidationFailures()
	 */
	public function validate($columns = null)
	{
		$res = $this->doValidate($columns);
		if ($res === true) {
			$this->validationFailures = array();
			return true;
		} else {
			$this->validationFailures = $res;
			return false;
		}
	}

	/**
	 * This function performs the validation work for complex object models.
	 *
	 * In addition to checking the current object, all related objects will
	 * also be validated.  If all pass then <code>true</code> is returned; otherwise
	 * an aggreagated array of ValidationFailed objects will be returned.
	 *
	 * @param      array $columns Array of column names to validate.
	 * @return     mixed <code>true</code> if all validations pass; array of <code>ValidationFailed</code> objets otherwise.
	 */
	protected function doValidate($columns = null)
	{
		if (!$this->alreadyInValidation) {
			$this->alreadyInValidation = true;
			$retval = null;

			$failureMap = array();


			// We call the validate method on the following object(s) if they
			// were passed to this object by their coresponding set
			// method.  This object relates to these object(s) by a
			// foreign key reference.

			if ($this->aCategory !== null) {
				if (!$this->aCategory->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCategory->getValidationFailures());
				}
			}

			if ($this->aElementStatus !== null) {
				if (!$this->aElementStatus->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aElementStatus->getValidationFailures());
				}
			}

			if ($this->aCompany !== null) {
				if (!$this->aCompany->validate($columns)) {
					$failureMap = array_merge($failureMap, $this->aCompany->getValidationFailures());
				}
			}


			if (($retval = ElementPeer::doValidate($this, $columns)) !== true) {
				$failureMap = array_merge($failureMap, $retval);
			}


				if ($this->collPreferences !== null) {
					foreach ($this->collPreferences as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collOrders !== null) {
					foreach ($this->collOrders as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}

				if ($this->collElementFiles !== null) {
					foreach ($this->collElementFiles as $referrerFK) {
						if (!$referrerFK->validate($columns)) {
							$failureMap = array_merge($failureMap, $referrerFK->getValidationFailures());
						}
					}
				}


			$this->alreadyInValidation = false;
		}

		return (!empty($failureMap) ? $failureMap : true);
	}

	/**
	 * Retrieves a field from the object by name passed in as a string.
	 *
	 * @param      string $name name
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     mixed Value of field.
	 */
	public function getByName($name, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ElementPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		$field = $this->getByPosition($pos);
		return $field;
	}

	/**
	 * Retrieves a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @return     mixed Value of field at $pos
	 */
	public function getByPosition($pos)
	{
		switch($pos) {
			case 0:
				return $this->getId();
				break;
			case 1:
				return $this->getCategoryId();
				break;
			case 2:
				return $this->getElementStatusId();
				break;
			case 3:
				return $this->getCompanyId();
				break;
			case 4:
				return $this->getName();
				break;
			case 5:
				return $this->getTitle();
				break;
			case 6:
				return $this->getDateCreated();
				break;
			case 7:
				return $this->getDateUpdated();
				break;
			case 8:
				return $this->getPreview();
				break;
			case 9:
				return $this->getDescription();
				break;
			case 10:
				return $this->getViewCount();
				break;
			case 11:
				return $this->getOrderCount();
				break;
			case 12:
				return $this->getOwnerPrice();
				break;
			case 13:
				return $this->getCompanyPrice();
				break;
			case 14:
				return $this->getPriceType();
				break;
			default:
				return null;
				break;
		} // switch()
	}

	/**
	 * Exports the object as an array.
	 *
	 * You can specify the key type of the array by passing one of the class
	 * type constants.
	 *
	 * @param      string $keyType (optional) One of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                        BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM. Defaults to BasePeer::TYPE_PHPNAME.
	 * @param      boolean $includeLazyLoadColumns (optional) Whether to include lazy loaded columns.  Defaults to TRUE.
	 * @return     an associative array containing the field names (as keys) and field values
	 */
	public function toArray($keyType = BasePeer::TYPE_PHPNAME, $includeLazyLoadColumns = true)
	{
		$keys = ElementPeer::getFieldNames($keyType);
		$result = array(
			$keys[0] => $this->getId(),
			$keys[1] => $this->getCategoryId(),
			$keys[2] => $this->getElementStatusId(),
			$keys[3] => $this->getCompanyId(),
			$keys[4] => $this->getName(),
			$keys[5] => $this->getTitle(),
			$keys[6] => $this->getDateCreated(),
			$keys[7] => $this->getDateUpdated(),
			$keys[8] => $this->getPreview(),
			$keys[9] => $this->getDescription(),
			$keys[10] => $this->getViewCount(),
			$keys[11] => $this->getOrderCount(),
			$keys[12] => $this->getOwnerPrice(),
			$keys[13] => $this->getCompanyPrice(),
			$keys[14] => $this->getPriceType(),
		);
		return $result;
	}

	/**
	 * Sets a field from the object by name passed in as a string.
	 *
	 * @param      string $name peer name
	 * @param      mixed $value field value
	 * @param      string $type The type of fieldname the $name is of:
	 *                     one of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME
	 *                     BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM
	 * @return     void
	 */
	public function setByName($name, $value, $type = BasePeer::TYPE_PHPNAME)
	{
		$pos = ElementPeer::translateFieldName($name, $type, BasePeer::TYPE_NUM);
		return $this->setByPosition($pos, $value);
	}

	/**
	 * Sets a field from the object by Position as specified in the xml schema.
	 * Zero-based.
	 *
	 * @param      int $pos position in xml schema
	 * @param      mixed $value field value
	 * @return     void
	 */
	public function setByPosition($pos, $value)
	{
		switch($pos) {
			case 0:
				$this->setId($value);
				break;
			case 1:
				$this->setCategoryId($value);
				break;
			case 2:
				$this->setElementStatusId($value);
				break;
			case 3:
				$this->setCompanyId($value);
				break;
			case 4:
				$this->setName($value);
				break;
			case 5:
				$this->setTitle($value);
				break;
			case 6:
				$this->setDateCreated($value);
				break;
			case 7:
				$this->setDateUpdated($value);
				break;
			case 8:
				$this->setPreview($value);
				break;
			case 9:
				$this->setDescription($value);
				break;
			case 10:
				$this->setViewCount($value);
				break;
			case 11:
				$this->setOrderCount($value);
				break;
			case 12:
				$this->setOwnerPrice($value);
				break;
			case 13:
				$this->setCompanyPrice($value);
				break;
			case 14:
				$this->setPriceType($value);
				break;
		} // switch()
	}

	/**
	 * Populates the object using an array.
	 *
	 * This is particularly useful when populating an object from one of the
	 * request arrays (e.g. $_POST).  This method goes through the column
	 * names, checking to see whether a matching key exists in populated
	 * array. If so the setByName() method is called for that column.
	 *
	 * You can specify the key type of the array by additionally passing one
	 * of the class type constants BasePeer::TYPE_PHPNAME, BasePeer::TYPE_STUDLYPHPNAME,
	 * BasePeer::TYPE_COLNAME, BasePeer::TYPE_FIELDNAME, BasePeer::TYPE_NUM.
	 * The default key type is the column's phpname (e.g. 'AuthorId')
	 *
	 * @param      array  $arr     An array to populate the object from.
	 * @param      string $keyType The type of keys the array uses.
	 * @return     void
	 */
	public function fromArray($arr, $keyType = BasePeer::TYPE_PHPNAME)
	{
		$keys = ElementPeer::getFieldNames($keyType);

		if (array_key_exists($keys[0], $arr)) $this->setId($arr[$keys[0]]);
		if (array_key_exists($keys[1], $arr)) $this->setCategoryId($arr[$keys[1]]);
		if (array_key_exists($keys[2], $arr)) $this->setElementStatusId($arr[$keys[2]]);
		if (array_key_exists($keys[3], $arr)) $this->setCompanyId($arr[$keys[3]]);
		if (array_key_exists($keys[4], $arr)) $this->setName($arr[$keys[4]]);
		if (array_key_exists($keys[5], $arr)) $this->setTitle($arr[$keys[5]]);
		if (array_key_exists($keys[6], $arr)) $this->setDateCreated($arr[$keys[6]]);
		if (array_key_exists($keys[7], $arr)) $this->setDateUpdated($arr[$keys[7]]);
		if (array_key_exists($keys[8], $arr)) $this->setPreview($arr[$keys[8]]);
		if (array_key_exists($keys[9], $arr)) $this->setDescription($arr[$keys[9]]);
		if (array_key_exists($keys[10], $arr)) $this->setViewCount($arr[$keys[10]]);
		if (array_key_exists($keys[11], $arr)) $this->setOrderCount($arr[$keys[11]]);
		if (array_key_exists($keys[12], $arr)) $this->setOwnerPrice($arr[$keys[12]]);
		if (array_key_exists($keys[13], $arr)) $this->setCompanyPrice($arr[$keys[13]]);
		if (array_key_exists($keys[14], $arr)) $this->setPriceType($arr[$keys[14]]);
	}

	/**
	 * Build a Criteria object containing the values of all modified columns in this object.
	 *
	 * @return     Criteria The Criteria object containing all modified values.
	 */
	public function buildCriteria()
	{
		$criteria = new Criteria(ElementPeer::DATABASE_NAME);

		if ($this->isColumnModified(ElementPeer::ID)) $criteria->add(ElementPeer::ID, $this->id);
		if ($this->isColumnModified(ElementPeer::CATEGORY_ID)) $criteria->add(ElementPeer::CATEGORY_ID, $this->category_id);
		if ($this->isColumnModified(ElementPeer::ELEMENT_STATUS_ID)) $criteria->add(ElementPeer::ELEMENT_STATUS_ID, $this->element_status_id);
		if ($this->isColumnModified(ElementPeer::COMPANY_ID)) $criteria->add(ElementPeer::COMPANY_ID, $this->company_id);
		if ($this->isColumnModified(ElementPeer::NAME)) $criteria->add(ElementPeer::NAME, $this->name);
		if ($this->isColumnModified(ElementPeer::TITLE)) $criteria->add(ElementPeer::TITLE, $this->title);
		if ($this->isColumnModified(ElementPeer::DATE_CREATED)) $criteria->add(ElementPeer::DATE_CREATED, $this->date_created);
		if ($this->isColumnModified(ElementPeer::DATE_UPDATED)) $criteria->add(ElementPeer::DATE_UPDATED, $this->date_updated);
		if ($this->isColumnModified(ElementPeer::PREVIEW)) $criteria->add(ElementPeer::PREVIEW, $this->preview);
		if ($this->isColumnModified(ElementPeer::DESCRIPTION)) $criteria->add(ElementPeer::DESCRIPTION, $this->description);
		if ($this->isColumnModified(ElementPeer::VIEW_COUNT)) $criteria->add(ElementPeer::VIEW_COUNT, $this->view_count);
		if ($this->isColumnModified(ElementPeer::ORDER_COUNT)) $criteria->add(ElementPeer::ORDER_COUNT, $this->order_count);
		if ($this->isColumnModified(ElementPeer::OWNER_PRICE)) $criteria->add(ElementPeer::OWNER_PRICE, $this->owner_price);
		if ($this->isColumnModified(ElementPeer::COMPANY_PRICE)) $criteria->add(ElementPeer::COMPANY_PRICE, $this->company_price);
		if ($this->isColumnModified(ElementPeer::PRICE_TYPE)) $criteria->add(ElementPeer::PRICE_TYPE, $this->price_type);

		return $criteria;
	}

	/**
	 * Builds a Criteria object containing the primary key for this object.
	 *
	 * Unlike buildCriteria() this method includes the primary key values regardless
	 * of whether or not they have been modified.
	 *
	 * @return     Criteria The Criteria object containing value(s) for primary key(s).
	 */
	public function buildPkeyCriteria()
	{
		$criteria = new Criteria(ElementPeer::DATABASE_NAME);

		$criteria->add(ElementPeer::ID, $this->id);

		return $criteria;
	}

	/**
	 * Returns the primary key for this object (row).
	 * @return     int
	 */
	public function getPrimaryKey()
	{
		return $this->getId();
	}

	/**
	 * Generic method to set the primary key (id column).
	 *
	 * @param      int $key Primary key.
	 * @return     void
	 */
	public function setPrimaryKey($key)
	{
		$this->setId($key);
	}

	/**
	 * Sets contents of passed object to values from current object.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      object $copyObj An object of Element (or compatible) type.
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @throws     PropelException
	 */
	public function copyInto($copyObj, $deepCopy = false)
	{

		$copyObj->setCategoryId($this->category_id);

		$copyObj->setElementStatusId($this->element_status_id);

		$copyObj->setCompanyId($this->company_id);

		$copyObj->setName($this->name);

		$copyObj->setTitle($this->title);

		$copyObj->setDateCreated($this->date_created);

		$copyObj->setDateUpdated($this->date_updated);

		$copyObj->setPreview($this->preview);

		$copyObj->setDescription($this->description);

		$copyObj->setViewCount($this->view_count);

		$copyObj->setOrderCount($this->order_count);

		$copyObj->setOwnerPrice($this->owner_price);

		$copyObj->setCompanyPrice($this->company_price);

		$copyObj->setPriceType($this->price_type);


		if ($deepCopy) {
			// important: temporarily setNew(false) because this affects the behavior of
			// the getter/setter methods for fkey referrer objects.
			$copyObj->setNew(false);

			foreach ($this->getPreferences() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addPreference($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getOrders() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addOrder($relObj->copy($deepCopy));
				}
			}

			foreach ($this->getElementFiles() as $relObj) {
				if ($relObj !== $this) {  // ensure that we don't try to copy a reference to ourselves
					$copyObj->addElementFile($relObj->copy($deepCopy));
				}
			}

		} // if ($deepCopy)


		$copyObj->setNew(true);

		$copyObj->setId(NULL); // this is a auto-increment column, so set to default value

	}

	/**
	 * Makes a copy of this object that will be inserted as a new row in table when saved.
	 * It creates a new object filling in the simple attributes, but skipping any primary
	 * keys that are defined for the table.
	 *
	 * If desired, this method can also make copies of all associated (fkey referrers)
	 * objects.
	 *
	 * @param      boolean $deepCopy Whether to also copy all rows that refer (by fkey) to the current row.
	 * @return     Element Clone of current object.
	 * @throws     PropelException
	 */
	public function copy($deepCopy = false)
	{
		// we use get_class(), because this might be a subclass
		$clazz = get_class($this);
		$copyObj = new $clazz();
		$this->copyInto($copyObj, $deepCopy);
		return $copyObj;
	}

	/**
	 * Returns a peer instance associated with this om.
	 *
	 * Since Peer classes are not to have any instance attributes, this method returns the
	 * same instance for all member of this class. The method could therefore
	 * be static, but this would prevent one from overriding the behavior.
	 *
	 * @return     ElementPeer
	 */
	public function getPeer()
	{
		if (self::$peer === null) {
			self::$peer = new ElementPeer();
		}
		return self::$peer;
	}

	/**
	 * Declares an association between this object and a Category object.
	 *
	 * @param      Category $v
	 * @return     Element The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCategory(Category $v = null)
	{
		if ($v === null) {
			$this->setCategoryId(NULL);
		} else {
			$this->setCategoryId($v->getId());
		}

		$this->aCategory = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Category object, it will not be re-added.
		if ($v !== null) {
			$v->addElement($this);
		}

		return $this;
	}


	/**
	 * Get the associated Category object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Category The associated Category object.
	 * @throws     PropelException
	 */
	public function getCategory(PropelPDO $con = null)
	{
		if ($this->aCategory === null && ($this->category_id !== null)) {
			$this->aCategory = CategoryPeer::retrieveByPk($this->category_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCategory->addElements($this);
			 */
		}
		return $this->aCategory;
	}

	/**
	 * Declares an association between this object and a ElementStatus object.
	 *
	 * @param      ElementStatus $v
	 * @return     Element The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setElementStatus(ElementStatus $v = null)
	{
		if ($v === null) {
			$this->setElementStatusId(NULL);
		} else {
			$this->setElementStatusId($v->getId());
		}

		$this->aElementStatus = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the ElementStatus object, it will not be re-added.
		if ($v !== null) {
			$v->addElement($this);
		}

		return $this;
	}


	/**
	 * Get the associated ElementStatus object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     ElementStatus The associated ElementStatus object.
	 * @throws     PropelException
	 */
	public function getElementStatus(PropelPDO $con = null)
	{
		if ($this->aElementStatus === null && ($this->element_status_id !== null)) {
			$this->aElementStatus = ElementStatusPeer::retrieveByPk($this->element_status_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aElementStatus->addElements($this);
			 */
		}
		return $this->aElementStatus;
	}

	/**
	 * Declares an association between this object and a Company object.
	 *
	 * @param      Company $v
	 * @return     Element The current object (for fluent API support)
	 * @throws     PropelException
	 */
	public function setCompany(Company $v = null)
	{
		if ($v === null) {
			$this->setCompanyId(NULL);
		} else {
			$this->setCompanyId($v->getId());
		}

		$this->aCompany = $v;

		// Add binding for other direction of this n:n relationship.
		// If this object has already been added to the Company object, it will not be re-added.
		if ($v !== null) {
			$v->addElement($this);
		}

		return $this;
	}


	/**
	 * Get the associated Company object
	 *
	 * @param      PropelPDO Optional Connection object.
	 * @return     Company The associated Company object.
	 * @throws     PropelException
	 */
	public function getCompany(PropelPDO $con = null)
	{
		if ($this->aCompany === null && ($this->company_id !== null)) {
			$this->aCompany = CompanyPeer::retrieveByPk($this->company_id);
			/* The following can be used additionally to
			   guarantee the related object contains a reference
			   to this object.  This level of coupling may, however, be
			   undesirable since it could result in an only partially populated collection
			   in the referenced object.
			   $this->aCompany->addElements($this);
			 */
		}
		return $this->aCompany;
	}

	/**
	 * Clears out the collPreferences collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addPreferences()
	 */
	public function clearPreferences()
	{
		$this->collPreferences = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collPreferences collection (array).
	 *
	 * By default this just sets the collPreferences collection to an empty array (like clearcollPreferences());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initPreferences()
	{
		$this->collPreferences = array();
	}

	/**
	 * Gets an array of Preference objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Element has previously been saved, it will retrieve
	 * related Preferences from storage. If this Element is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Preference[]
	 * @throws     PropelException
	 */
	public function getPreferences($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ElementPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPreferences === null) {
			if ($this->isNew()) {
			   $this->collPreferences = array();
			} else {

				$criteria->add(PreferencePeer::ELEMENT_ID, $this->id);

				PreferencePeer::addSelectColumns($criteria);
				$this->collPreferences = PreferencePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(PreferencePeer::ELEMENT_ID, $this->id);

				PreferencePeer::addSelectColumns($criteria);
				if (!isset($this->lastPreferenceCriteria) || !$this->lastPreferenceCriteria->equals($criteria)) {
					$this->collPreferences = PreferencePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastPreferenceCriteria = $criteria;
		return $this->collPreferences;
	}

	/**
	 * Returns the number of related Preference objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Preference objects.
	 * @throws     PropelException
	 */
	public function countPreferences(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ElementPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collPreferences === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(PreferencePeer::ELEMENT_ID, $this->id);

				$count = PreferencePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(PreferencePeer::ELEMENT_ID, $this->id);

				if (!isset($this->lastPreferenceCriteria) || !$this->lastPreferenceCriteria->equals($criteria)) {
					$count = PreferencePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collPreferences);
				}
			} else {
				$count = count($this->collPreferences);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Preference object to this object
	 * through the Preference foreign key attribute.
	 *
	 * @param      Preference $l Preference
	 * @return     void
	 * @throws     PropelException
	 */
	public function addPreference(Preference $l)
	{
		if ($this->collPreferences === null) {
			$this->initPreferences();
		}
		if (!in_array($l, $this->collPreferences, true)) { // only add it if the **same** object is not already associated
			array_push($this->collPreferences, $l);
			$l->setElement($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Element is new, it will return
	 * an empty collection; or if this Element has previously
	 * been saved, it will retrieve related Preferences from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Element.
	 */
	public function getPreferencesJoinCategoryPreference($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ElementPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collPreferences === null) {
			if ($this->isNew()) {
				$this->collPreferences = array();
			} else {

				$criteria->add(PreferencePeer::ELEMENT_ID, $this->id);

				$this->collPreferences = PreferencePeer::doSelectJoinCategoryPreference($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(PreferencePeer::ELEMENT_ID, $this->id);

			if (!isset($this->lastPreferenceCriteria) || !$this->lastPreferenceCriteria->equals($criteria)) {
				$this->collPreferences = PreferencePeer::doSelectJoinCategoryPreference($criteria, $con, $join_behavior);
			}
		}
		$this->lastPreferenceCriteria = $criteria;

		return $this->collPreferences;
	}

	/**
	 * Clears out the collOrders collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addOrders()
	 */
	public function clearOrders()
	{
		$this->collOrders = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collOrders collection (array).
	 *
	 * By default this just sets the collOrders collection to an empty array (like clearcollOrders());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initOrders()
	{
		$this->collOrders = array();
	}

	/**
	 * Gets an array of Order objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Element has previously been saved, it will retrieve
	 * related Orders from storage. If this Element is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array Order[]
	 * @throws     PropelException
	 */
	public function getOrders($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ElementPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOrders === null) {
			if ($this->isNew()) {
			   $this->collOrders = array();
			} else {

				$criteria->add(OrderPeer::ELEMENT_ID, $this->id);

				OrderPeer::addSelectColumns($criteria);
				$this->collOrders = OrderPeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(OrderPeer::ELEMENT_ID, $this->id);

				OrderPeer::addSelectColumns($criteria);
				if (!isset($this->lastOrderCriteria) || !$this->lastOrderCriteria->equals($criteria)) {
					$this->collOrders = OrderPeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastOrderCriteria = $criteria;
		return $this->collOrders;
	}

	/**
	 * Returns the number of related Order objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related Order objects.
	 * @throws     PropelException
	 */
	public function countOrders(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ElementPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collOrders === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(OrderPeer::ELEMENT_ID, $this->id);

				$count = OrderPeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(OrderPeer::ELEMENT_ID, $this->id);

				if (!isset($this->lastOrderCriteria) || !$this->lastOrderCriteria->equals($criteria)) {
					$count = OrderPeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collOrders);
				}
			} else {
				$count = count($this->collOrders);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a Order object to this object
	 * through the Order foreign key attribute.
	 *
	 * @param      Order $l Order
	 * @return     void
	 * @throws     PropelException
	 */
	public function addOrder(Order $l)
	{
		if ($this->collOrders === null) {
			$this->initOrders();
		}
		if (!in_array($l, $this->collOrders, true)) { // only add it if the **same** object is not already associated
			array_push($this->collOrders, $l);
			$l->setElement($this);
		}
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Element is new, it will return
	 * an empty collection; or if this Element has previously
	 * been saved, it will retrieve related Orders from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Element.
	 */
	public function getOrdersJoinOrderStatus($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ElementPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOrders === null) {
			if ($this->isNew()) {
				$this->collOrders = array();
			} else {

				$criteria->add(OrderPeer::ELEMENT_ID, $this->id);

				$this->collOrders = OrderPeer::doSelectJoinOrderStatus($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OrderPeer::ELEMENT_ID, $this->id);

			if (!isset($this->lastOrderCriteria) || !$this->lastOrderCriteria->equals($criteria)) {
				$this->collOrders = OrderPeer::doSelectJoinOrderStatus($criteria, $con, $join_behavior);
			}
		}
		$this->lastOrderCriteria = $criteria;

		return $this->collOrders;
	}


	/**
	 * If this collection has already been initialized with
	 * an identical criteria, it returns the collection.
	 * Otherwise if this Element is new, it will return
	 * an empty collection; or if this Element has previously
	 * been saved, it will retrieve related Orders from storage.
	 *
	 * This method is protected by default in order to keep the public
	 * api reasonable.  You can provide public methods for those you
	 * actually need in Element.
	 */
	public function getOrdersJoinClient($criteria = null, $con = null, $join_behavior = Criteria::LEFT_JOIN)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ElementPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collOrders === null) {
			if ($this->isNew()) {
				$this->collOrders = array();
			} else {

				$criteria->add(OrderPeer::ELEMENT_ID, $this->id);

				$this->collOrders = OrderPeer::doSelectJoinClient($criteria, $con, $join_behavior);
			}
		} else {
			// the following code is to determine if a new query is
			// called for.  If the criteria is the same as the last
			// one, just return the collection.

			$criteria->add(OrderPeer::ELEMENT_ID, $this->id);

			if (!isset($this->lastOrderCriteria) || !$this->lastOrderCriteria->equals($criteria)) {
				$this->collOrders = OrderPeer::doSelectJoinClient($criteria, $con, $join_behavior);
			}
		}
		$this->lastOrderCriteria = $criteria;

		return $this->collOrders;
	}

	/**
	 * Clears out the collElementFiles collection (array).
	 *
	 * This does not modify the database; however, it will remove any associated objects, causing
	 * them to be refetched by subsequent calls to accessor method.
	 *
	 * @return     void
	 * @see        addElementFiles()
	 */
	public function clearElementFiles()
	{
		$this->collElementFiles = null; // important to set this to NULL since that means it is uninitialized
	}

	/**
	 * Initializes the collElementFiles collection (array).
	 *
	 * By default this just sets the collElementFiles collection to an empty array (like clearcollElementFiles());
	 * however, you may wish to override this method in your stub class to provide setting appropriate
	 * to your application -- for example, setting the initial array to the values stored in database.
	 *
	 * @return     void
	 */
	public function initElementFiles()
	{
		$this->collElementFiles = array();
	}

	/**
	 * Gets an array of ElementFile objects which contain a foreign key that references this object.
	 *
	 * If this collection has already been initialized with an identical Criteria, it returns the collection.
	 * Otherwise if this Element has previously been saved, it will retrieve
	 * related ElementFiles from storage. If this Element is new, it will return
	 * an empty collection or the current collection, the criteria is ignored on a new object.
	 *
	 * @param      PropelPDO $con
	 * @param      Criteria $criteria
	 * @return     array ElementFile[]
	 * @throws     PropelException
	 */
	public function getElementFiles($criteria = null, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ElementPeer::DATABASE_NAME);
		}
		elseif ($criteria instanceof Criteria)
		{
			$criteria = clone $criteria;
		}

		if ($this->collElementFiles === null) {
			if ($this->isNew()) {
			   $this->collElementFiles = array();
			} else {

				$criteria->add(ElementFilePeer::ELEMENT_ID, $this->id);

				ElementFilePeer::addSelectColumns($criteria);
				$this->collElementFiles = ElementFilePeer::doSelect($criteria, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return the collection.


				$criteria->add(ElementFilePeer::ELEMENT_ID, $this->id);

				ElementFilePeer::addSelectColumns($criteria);
				if (!isset($this->lastElementFileCriteria) || !$this->lastElementFileCriteria->equals($criteria)) {
					$this->collElementFiles = ElementFilePeer::doSelect($criteria, $con);
				}
			}
		}
		$this->lastElementFileCriteria = $criteria;
		return $this->collElementFiles;
	}

	/**
	 * Returns the number of related ElementFile objects.
	 *
	 * @param      Criteria $criteria
	 * @param      boolean $distinct
	 * @param      PropelPDO $con
	 * @return     int Count of related ElementFile objects.
	 * @throws     PropelException
	 */
	public function countElementFiles(Criteria $criteria = null, $distinct = false, PropelPDO $con = null)
	{
		if ($criteria === null) {
			$criteria = new Criteria(ElementPeer::DATABASE_NAME);
		} else {
			$criteria = clone $criteria;
		}

		if ($distinct) {
			$criteria->setDistinct();
		}

		$count = null;

		if ($this->collElementFiles === null) {
			if ($this->isNew()) {
				$count = 0;
			} else {

				$criteria->add(ElementFilePeer::ELEMENT_ID, $this->id);

				$count = ElementFilePeer::doCount($criteria, false, $con);
			}
		} else {
			// criteria has no effect for a new object
			if (!$this->isNew()) {
				// the following code is to determine if a new query is
				// called for.  If the criteria is the same as the last
				// one, just return count of the collection.


				$criteria->add(ElementFilePeer::ELEMENT_ID, $this->id);

				if (!isset($this->lastElementFileCriteria) || !$this->lastElementFileCriteria->equals($criteria)) {
					$count = ElementFilePeer::doCount($criteria, false, $con);
				} else {
					$count = count($this->collElementFiles);
				}
			} else {
				$count = count($this->collElementFiles);
			}
		}
		return $count;
	}

	/**
	 * Method called to associate a ElementFile object to this object
	 * through the ElementFile foreign key attribute.
	 *
	 * @param      ElementFile $l ElementFile
	 * @return     void
	 * @throws     PropelException
	 */
	public function addElementFile(ElementFile $l)
	{
		if ($this->collElementFiles === null) {
			$this->initElementFiles();
		}
		if (!in_array($l, $this->collElementFiles, true)) { // only add it if the **same** object is not already associated
			array_push($this->collElementFiles, $l);
			$l->setElement($this);
		}
	}

	/**
	 * Resets all collections of referencing foreign keys.
	 *
	 * This method is a user-space workaround for PHP's inability to garbage collect objects
	 * with circular references.  This is currently necessary when using Propel in certain
	 * daemon or large-volumne/high-memory operations.
	 *
	 * @param      boolean $deep Whether to also clear the references on all associated objects.
	 */
	public function clearAllReferences($deep = false)
	{
		if ($deep) {
			if ($this->collPreferences) {
				foreach ((array) $this->collPreferences as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collOrders) {
				foreach ((array) $this->collOrders as $o) {
					$o->clearAllReferences($deep);
				}
			}
			if ($this->collElementFiles) {
				foreach ((array) $this->collElementFiles as $o) {
					$o->clearAllReferences($deep);
				}
			}
		} // if ($deep)

		$this->collPreferences = null;
		$this->collOrders = null;
		$this->collElementFiles = null;
			$this->aCategory = null;
			$this->aElementStatus = null;
			$this->aCompany = null;
	}

	// symfony_behaviors behavior
	
	/**
	 * Calls methods defined via {@link sfMixer}.
	 */
	public function __call($method, $arguments)
	{
	  if (!$callable = sfMixer::getCallable('BaseElement:'.$method))
	  {
	    throw new sfException(sprintf('Call to undefined method BaseElement::%s', $method));
	  }
	
	  array_unshift($arguments, $this);
	
	  return call_user_func_array($callable, $arguments);
	}

} // BaseElement
