<?php
// auto-generated by sfDatabaseConfigHandler
// date: 2010/02/01 17:34:09

return array(
'propel' => new sfPropelDatabase(array (
  'classname' => 'PropelPDO',
  'dsn' => 'mysql:dbname=lk-broker;host=lk-broker.ru',
  'username' => 'megbroker',
  'password' => 'qwe123',
  'encoding' => 'utf8',
  'persistent' => true,
  'pooling' => true,
  'name' => 'propel',
)),);
