# default rules
homepage:
  url:   /
  param: { module: page, action: index }

element:
  url:   /catalog/:category_name/:element_id
  param: { module: element, action: view }

catalog:
  url:   /catalog/:category_name
  param: { module: category, action: view }

page:
  url:   /:name
  param: { module: page, action: view }

# generic rules
default_index:
  url:   /:module
  param: { action: index }

default:
  url:   /:module/:action/*
