generator:
  class: sfPropelGenerator
  param:
    model_class:           Element
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Element
    plural:                Elements
    route_prefix:          element
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new: {label: создать} 
        _edit: {label: изменить} 
        _delete: {label: удалить} 
        _save: {label: сохранить} 
        _save_and_add: {label: сохранить и добавить} 
        _list: {label: показать все}
      fields:
        name: {label: Название, help: ''}
        title: {label: Заголовок, help: заголовок элемента}
        category_id: {label: Категория, help: категория элемента}
        description: {label: Описание элемента, help: раширенное описание элемента}
        preview: {label: Описание элемента, help: краткое описание элемента}
        element_status_id: {label: Статус, help: ''}
        owner_price: {label: Цена продавца, help: ''}
        company_price: {label: Цена компании, help: ''}
      list:
        title: Элементы
        display: [name]
        max_per_page: 20
      filter:  ~
      form:    ~
      edit:
        title: Редактированние элемента %%name%%
      new:
        title: Добавление нового элемента