<?php


/**
 * Skeleton subclass for performing query and update operations on the 'category_preference' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Tue Jan 12 12:50:28 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class CategoryPreferencePeer extends BaseCategoryPreferencePeer {

	public static function getPreferenceByCategoryId($id)
	{
		$c = new Criteria();
		$c->add(self::CATEGORY_ID, intval($id));
		
		return self::doSelect($c);
	}

} // CategoryPreferencePeer
