<?php


/**
 * Skeleton subclass for representing a row from the 'modx_site_content' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Fri Jan 29 18:00:37 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class Content extends BaseContent {

} // Content
