<?php


/**
 * Skeleton subclass for representing a row from the 'modx_company' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.1 on:
 *
 * Thu Jan 28 14:50:10 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class OldCompany extends BaseOldCompany {

} // OldCompany
