<?php


/**
 * Skeleton subclass for performing query and update operations on the 'page' table.
 *
 * 
 *
 * This class was autogenerated by Propel 1.4.0 on:
 *
 * Thu Jan 14 16:10:33 2010
 *
 * You should add additional methods to this class to meet the
 * application requirements.  This class will only be generated as
 * long as it does not already exist in the output directory.
 *
 * @package    lib.model
 */
class PagePeer extends BasePagePeer 
{
	public static function retrieveByName($name)
	{
		$c = new Criteria();
		$c->add(PagePeer::NAME, $name);
		
		return self::doSelectOne($c);
	}
	
	public static function getList()
	{
		$c = new Criteria();
		
		return self::doSelect($c);
	}
} // PagePeer
