generator:
  class: sfPropelGenerator
  param:
    model_class:           Category
    theme:                 admin
    non_verbose_templates: true
    with_show:             false
    singular:              Category
    plural:                Categorys
    route_prefix:          category
    with_propel_route:     1
    actions_base_class:    sfActions

    config:
      actions:
        _new: {label: создать} 
        _edit: {label: изменить} 
        _delete: {label: удалить} 
        _save: {label: сохранить} 
        _save_and_add: {label: сохранить и добавить} 
        _list: {label: показать все} 
      fields:
        header: {label: Заголовок, help: заголовок категории}
        name: {label: Системное имя, help: уникальный идентификатор}
        parent_id: {label: Родительская категория, help: если 0 то данная категория является родительской}
        description: {label: Описание категории, help: краткое описание категории}
      list:
        title: 'Категории'
        display: [=name, =header]
        max_per_page: 20
        batch_actions: {} 
      filter:
        display: [name, header]
      form:
        display: [header, name, description]
      edit:
        title: Редактированние категории %%header%%
      new:
        title: Добавление новой категории
